config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # resources :movies
  # resources :lists

  # A user can see all the lists - OK
  # get 'lists', to: 'lists#index'

  # A user can see the details of a given list and its name
  # get 'lists/:id', to: 'lists#show'

  # A user can add a new bookmark (movie/list pair) to an existing list
  # Checkout simple_form docs about f.association to easily create a select dropdown for our list of movies.

  resources :bookmarks, only: [:destroy]
  resources :lists, only: [:new, :create]
  resources :lists, only: [:index, :show] do
    resources :bookmarks, only: [:new, :create]
  end



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates_uniqueness_of :movie_id, scope: [:list_id]
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, :dependent => :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true
  validates :title, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list , except: [:destroy]

  def new
    @bookmark = @list.bookmarks.new
  end

  def create
    @bookmark = @list.bookmarks.new(bookmarks_params)
    if @bookmark.save
      redirect_to @list
    else
      render :new
    end
  end

  def destroy
    bookmark = Bookmark.find(params[:id])
    bookmark.destroy
    redirect_to list_path(bookmark.list_id)
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def bookmarks_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id )
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end
  def create
    list = List.new(list_params)
    if list.save
      redirect_to lists_path
    else
      render :new
    end
  end
  def new
    @list = List.new
  end
  def edit
  end
  def show
    @list = List.find(params[:id])
    @bookmarks = @list.bookmarks
    # @movie = Movie.find(@boo)
    # @bookmark = @list.bookmark
  end
  def update
  end
  def destroy
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
  end
  def create
  end
  def new
  end
  def edit
  end
  def show
  end
  def update
  end
  def destroy
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<div class="container">
  <%= simple_form_for [ @list, @bookmark ] do |f| %>
    <%= f.input :comment %>
    <%# <%= f.hidden_field :list_id, value: params[:list_id]  %>
    <%= f.association :movie %>
    <%= f.button :submit %>
  <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">
          <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" />
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Messages</a>
            </li>
            <li class="nav-item dropdown">
              <img class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://kitt.lewagon.com/placeholder/users/ssaunier" />
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
              </div>
            </li>
            <!--li class="nav-item"-->
            <!--/li-->
          </ul>
        </div>
      </div>
    </div>
    <%= yield %>
  </body>
</html>

app/views/lists/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/background.png);">
  <div class="container">
    <h1><strong>Save any kind of movie</strong>!</h1>
    <p>Your full application to watched movies from stream platform.</p>
  </div>
</div>

app/views/lists/index.html.erb
<%= render 'banner' %>

<div class="container">
  <h2>My list</h2>
  <div class="cards">
    <% @lists.each_with_index do |list, index| %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg)">
        <%= link_to list.name, list_path(list) %>
      </div>
    <% end %>
  </div>
  <%= link_to "Add List", new_list_path, class: "btn btn-flat" %>
</div>

app/views/lists/new.html.erb
<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.button :submit %>
<% end %>

app/views/lists/show.html.erb
<%= render 'banner' %>

<%= link_to 'Add movie', new_list_bookmark_path(@list), class:"btn btn-flat" %>


<div class="container">
  <div class="cards">
    <% @bookmarks.each do |bookmark| %>
      <div class="card-trip">
        <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/greece.jpg" />
        <div class="card-trip-infos">
          <div>
            <h2><%= Movie.find(bookmark.movie_id).title %></h2>
            <p><%= Movie.find(bookmark.movie_id).rating %> </p>
          </div>
          <p class="card-trip-pricing"><%= Movie.find(bookmark.movie_id).overview %></p>
          <div>
            <p><%= bookmark.comment %></p>
            <%= link_to 'delete', bookmark_path(bookmark), method: :delete %>
            <%# <%= link_to 'delete', list_bookmark_path(@bookmark)  %>
          </div>
        </div>
      </div>
    <% end  %>
  </div>
</div>

app/views/movies/edit.html.erb
<h1>Edit Movies</h1>

app/views/movies/index.html.erb
<h1>Index Movies</h1>

app/views/movies/new.html.erb
<h1>Add a new Movie</h1>

app/views/movies/show.html.erb
<h1>Show Movies</h1>